/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package recurso;



///otros //
import javax.swing.BorderFactory;
import javax.swing.border.Border;
import java.util.List;
import java.util.Date;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.awt.Color;
//////////



import javax.swing.JOptionPane;
import java.time.LocalDateTime;

/**
 *
 * @author Gui26
 */
public class LimitePago extends javax.swing.JFrame {
    
    
    /**
     * Creates new form LimitePago
     */
    public LimitePago() {
        initComponents();
        btnAplicar.setVisible(false);
        lblCupon.setVisible(false);
        txtNumeroCupon.setVisible(false);
        lblDescuento.setVisible(false);
        lblTotalConDescuento.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Agrupador = new javax.swing.JPanel();
        btnRealizaPago = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblCvv = new javax.swing.JLabel();
        txtCvv = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        lblCorreoNombre = new javax.swing.JLabel();
        txtCorreoNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbMetodo = new javax.swing.JComboBox<>();
        lblTotal = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        panelMenu = new javax.swing.JPanel();
        btnCarrito1 = new javax.swing.JButton();
        btnCerrarSesion1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        labelErrorTarjeta = new javax.swing.JLabel();
        labelErrorNombre = new javax.swing.JLabel();
        labelErrorFechaCaducidad = new javax.swing.JLabel();
        labelErrorCVV = new javax.swing.JLabel();
        rbCupon = new javax.swing.JRadioButton();
        btnAplicar = new javax.swing.JToggleButton();
        txtNumeroCupon = new javax.swing.JTextField();
        lblCupon = new javax.swing.JLabel();
        lblDescuento = new javax.swing.JLabel();
        lblTotalConDescuento = new javax.swing.JLabel();
        datePicker1 = new com.github.lgooddatepicker.components.DatePicker();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pantalla de pago");

        Agrupador.setBackground(new java.awt.Color(255, 255, 255));
        Agrupador.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRealizaPago.setBackground(new java.awt.Color(0, 102, 153));
        btnRealizaPago.setForeground(new java.awt.Color(255, 255, 255));
        btnRealizaPago.setText("Pagar");
        btnRealizaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealizaPagoActionPerformed(evt);
            }
        });
        Agrupador.add(btnRealizaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, 100, 40));

        btnCancelar.setBackground(new java.awt.Color(0, 102, 153));
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        Agrupador.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, 40));

        lblCvv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCvv.setForeground(new java.awt.Color(0, 0, 0));
        lblCvv.setText("CVV:");
        Agrupador.add(lblCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        txtCvv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCvvKeyTyped(evt);
            }
        });
        Agrupador.add(txtCvv, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 152, -1));

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(0, 0, 0));
        lblFecha.setText("Fecha de caducidad:");
        Agrupador.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lblCorreoNombre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCorreoNombre.setForeground(new java.awt.Color(0, 0, 0));
        lblCorreoNombre.setText("Nombre:");
        Agrupador.add(lblCorreoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        txtCorreoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCorreoNombreKeyTyped(evt);
            }
        });
        Agrupador.add(txtCorreoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 152, -1));

        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });
        Agrupador.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 152, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Numero:");
        Agrupador.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Metodo de pago:");
        Agrupador.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 10));

        cbMetodo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta Bancaria", "Transferencia Bancaria" }));
        cbMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMetodoActionPerformed(evt);
            }
        });
        Agrupador.add(cbMetodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, -1, -1));

        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Agrupador.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 152, 25));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Total:");
        Agrupador.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 25));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Datos sobre pago");
        Agrupador.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 20));

        panelMenu.setBackground(new java.awt.Color(0, 102, 153));

        btnCarrito1.setBackground(new java.awt.Color(0, 102, 153));
        btnCarrito1.setForeground(new java.awt.Color(51, 51, 51));
        btnCarrito1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/carrito-compras.png"))); // NOI18N
        btnCarrito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarrito1ActionPerformed(evt);
            }
        });

        btnCerrarSesion1.setText("Cerrar sesion");
        btnCerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 102, 153));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/userBOTON.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnCerrarSesion1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 395, Short.MAX_VALUE)
                .addComponent(btnCarrito1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarrito1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnCerrarSesion1, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        Agrupador.add(panelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tarjeta-de-credito (1).png"))); // NOI18N
        Agrupador.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 180, 190));

        labelErrorTarjeta.setToolTipText("");
        Agrupador.add(labelErrorTarjeta, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));
        Agrupador.add(labelErrorNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, -1));

        labelErrorFechaCaducidad.setToolTipText("");
        Agrupador.add(labelErrorFechaCaducidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        labelErrorCVV.setToolTipText("");
        Agrupador.add(labelErrorCVV, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));

        rbCupon.setForeground(new java.awt.Color(0, 0, 0));
        rbCupon.setText("Cupon");
        rbCupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCuponActionPerformed(evt);
            }
        });
        Agrupador.add(rbCupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, -1, -1));

        btnAplicar.setText("AplicarCupon");
        btnAplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarActionPerformed(evt);
            }
        });
        Agrupador.add(btnAplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(473, 270, 110, -1));

        txtNumeroCupon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCuponActionPerformed(evt);
            }
        });
        Agrupador.add(txtNumeroCupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 100, -1));

        lblCupon.setForeground(new java.awt.Color(0, 0, 0));
        lblCupon.setText("Numero de cupon:");
        Agrupador.add(lblCupon, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, -1, -1));

        lblDescuento.setForeground(new java.awt.Color(0, 0, 0));
        lblDescuento.setText("Total con descuento aplicado:");
        Agrupador.add(lblDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        lblTotalConDescuento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalConDescuento.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Agrupador.add(lblTotalConDescuento, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 350, 100, 20));
        Agrupador.add(datePicker1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Agrupador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Agrupador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMetodoActionPerformed
        
    }//GEN-LAST:event_cbMetodoActionPerformed

 
    
    private void btnRealizaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealizaPagoActionPerformed
  
    }//GEN-LAST:event_btnRealizaPagoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        LimiteCarrito limite = new LimiteCarrito();
        limite.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCarrito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarrito1ActionPerformed
        LimiteCarrito limite = new LimiteCarrito();
        limite.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCarrito1ActionPerformed

    private void btnCerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion1ActionPerformed
        LogIn limite = new LogIn();
        limite.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnCerrarSesion1ActionPerformed

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
         
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void txtCorreoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoNombreKeyTyped

    }//GEN-LAST:event_txtCorreoNombreKeyTyped

    private void txtCvvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCvvKeyTyped
                   char c = evt.getKeyChar();
    if (!Character.isDigit(c)) {
        evt.consume(); 
          }
    }//GEN-LAST:event_txtCvvKeyTyped

    private void rbCuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCuponActionPerformed
    }//GEN-LAST:event_rbCuponActionPerformed

    private void btnAplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarActionPerformed
        
    }//GEN-LAST:event_btnAplicarActionPerformed

    private void txtNumeroCuponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCuponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCuponActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jButton1ActionPerformed

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Agrupador;
    private javax.swing.JToggleButton btnAplicar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCarrito1;
    private javax.swing.JButton btnCerrarSesion1;
    private javax.swing.JButton btnRealizaPago;
    private javax.swing.JComboBox<String> cbMetodo;
    private com.github.lgooddatepicker.components.DatePicker datePicker1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelErrorCVV;
    private javax.swing.JLabel labelErrorFechaCaducidad;
    private javax.swing.JLabel labelErrorNombre;
    private javax.swing.JLabel labelErrorTarjeta;
    private javax.swing.JLabel lblCorreoNombre;
    private javax.swing.JLabel lblCupon;
    private javax.swing.JLabel lblCvv;
    private javax.swing.JLabel lblDescuento;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblTotalConDescuento;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JRadioButton rbCupon;
    private javax.swing.JTextField txtCorreoNombre;
    private javax.swing.JTextField txtCvv;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtNumeroCupon;
    // End of variables declaration//GEN-END:variables
}
